### ISSUE TITLE
May need some help

### ISSUE THREAD

**Issue by Char1x4** [iamgmujtaba/dash-server#1]
Hello,

I am a student of Louisiana State University, recently I am trying using this repo to start a local server.

I processed the BBB video with ffmpeg, Video seems divided into 5 streams. However the VLC only plays the last one.

Any ideas?

Thanks a lot

**Comment by Char1x4** [comment]
okey your trimmed video process with script seems work. I think I will just use the script and try again.

**Comment by Char1x4** [comment]
it still only plays the last one.

**Comment by iamgmujtaba** [comment]
Did you check the mpd file? does it contain all the video chunks?

you can test ```python .\main.py -i .\input\ -o .\output\``` this command in order to generate video segments.
Try some other videos to check if you are facing the issues.
